version: "3.9"

services:
  fsb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fsb
    restart: always
    volumes:
      - ./logs:/app/logs
    env_file:
      - fsb.env
    ports:
      - "8038:8080"